import { StandardButton, TextEdit } from "std-widgets.slint";

export component ImportPGN_UI inherits Dialog {
    title: "Import FEN";
    icon: @image-url("resources/chesslogo.png");
    default-font-family: "CaskaydiaCove Nerd Font";
    width: 400px;
    height: 450px;
    always-on-top: true;

    in property <bool> error: false;
    in property <string> error-message: "";
    in property <string> pgn_str <=> pgn.text;

    callback import-pgn(string);
    callback close();

    VerticalLayout {
        alignment: LayoutAlignment.stretch;
        spacing: 10px;

        Text {
            text: "Import PGN:";
            font-size: 14px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        pgn := TextEdit {
            wrap: word-wrap;
            max-width: root.width;
            height: 75%;
            text: "";
            placeholder-text: "Enter PGN";
            font-size: 12px;
            read-only: false;
        }
        
        Text {
            text: "Error: " + error-message;
            color: red;
            visible: error;
            font-size: 10px;
            wrap: word-wrap;
            vertical-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            spacing: 10px;
            StandardButton {
                kind: ok;
                clicked => {
                    import-pgn(pgn.text);
                }
            }

            StandardButton {
                kind: cancel;
                clicked => {
                    close();
                }
            }
        }
    }

}