import { LineEdit, StandardButton, CheckBox } from "std-widgets.slint";

export component ImportFen_UI inherits Dialog {
    title: "Import FEN";
    icon: @image-url("resources/chesslogo.png");
    default-font-family: "CaskaydiaCove Nerd Font";
    width: 400px;
    height: 200px;
    always-on-top: true;

    in property <bool> error: false;
    in property <string> error-message: "";
    in property <string> fen_str <=> fen.text;
    in property <bool> as-white <=> side.checked;
    //side.current-value == "White" ? true : false;

    callback import-fen(string);
    callback close();

    VerticalLayout {
        alignment: center;
        spacing: 10px;
        fen := LineEdit {
            text: "";
            placeholder-text: "Enter FEN";
            read-only: false;
        }

        Text {
            text: "Error: " + error-message;
            color: red;
            visible: error;
            font-size: 10px;
            wrap: word-wrap;
            vertical-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            spacing: 10px;
            StandardButton {
                kind: ok;
                clicked => {
                    import-fen(fen.text);
                }
            }

            StandardButton {
                kind: cancel;
                clicked => {
                    close();
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            Text {
                text: "Play as white ";
                vertical-alignment: center;
            }

            side := CheckBox {
                checked: true;
            }
        }
    }
}
